/*
	This file gets automatically generated by makefile

	Its purpose is to configure each liblightmodbus header file,
	so the user does not have to pass tons of compiler options each time
	he/she wants to compile the library.
	It also serves as a pretty nice source of information about current
	library setup.

	Do not edit this file manually unless you know what you are doing.
*/
#ifndef LIGHTMODBUS_LIBCONF_H
#define LIGHTMODBUS_LIBCONF_H
#define LIGHTMODBUS_VERSION "v1.2-244-gd8ae2e-dirty"
#define LIGHTMODBUS_F01S
#define LIGHTMODBUS_F02S
#define LIGHTMODBUS_F03S
#define LIGHTMODBUS_F04S
#define LIGHTMODBUS_F05S
#define LIGHTMODBUS_F06S
#define LIGHTMODBUS_F15S
#define LIGHTMODBUS_F16S
#define LIGHTMODBUS_F22S
#define LIGHTMODBUS_F01M
#define LIGHTMODBUS_F02M
#define LIGHTMODBUS_F03M
#define LIGHTMODBUS_F04M
#define LIGHTMODBUS_F05M
#define LIGHTMODBUS_F06M
#define LIGHTMODBUS_F15M
#define LIGHTMODBUS_F16M
#define LIGHTMODBUS_F22M

#define LIGHTMODBUS_STATIC_MEM_SLAVE_RESPONSE 256
#define LIGHTMODBUS_STATIC_MEM_SLAVE_REQUEST 256

#endif
